export default [
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        performance: 'readonly',
        localStorage: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        DragEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        Node: 'readonly',
        Element: 'readonly',
        DocumentFragment: 'readonly',
        module: 'readonly',
        Worker: 'readonly',
        self: 'readonly',
        importScripts: 'readonly',
        GPUShaderStage: 'readonly',
        GPUBufferUsage: 'readonly',
        GPUTextureUsage: 'readonly',
        // Global app modules
        API: 'writable',
        App: 'writable',
        Batch: 'writable',
        BatchOps: 'writable',
        CommandPalette: 'writable',
        CompareMode: 'writable',
        ContextMenu: 'writable',
        Editor: 'writable',
        Filmstrip: 'writable',
        Gallery: 'writable',
        GPURenderer: 'writable',
        GridLogic: 'writable',
        Logger: 'writable',
        MapModule: 'writable',
        Search: 'writable',
        Settings: 'writable',
        Shortcuts: 'writable',
        Sidebar: 'writable',
        Slideshow: 'writable',
        Tags: 'writable',
        Timeline: 'writable',
        Trash: 'writable',
        Updater: 'writable',
        Utils: 'writable',
        Viewer: 'writable',
        VirtualGrid: 'writable',
        Welcome: 'writable',
        WiPhotoMap: 'writable',
        L: 'writable',
        Supercluster: 'writable',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-redeclare': 'error',
      'no-dupe-keys': 'error',
      'no-unreachable': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
  {
    ignores: ['src/lib/**', 'src/**/*.test.cjs'],
  },
];
